version: "3.8"

services:
  streaming-server:
    container_name: streaming-server
    image: alfg/nginx-rtmp
    ports:
      - 420:420
      - 7002:7002
    networks:
      backend-network:
    depends_on:
      - backend
    volumes:
    - type: volume
      source: recordings
      target: /recordings
    - ./streaming-backend/nginx.conf:/etc/nginx/nginx.conf.template
    restart: always

  backend:
    container_name: backend_container
    depends_on:
      - db
    build: .
    networks:
      backend-network:
    ports:
      - 8080:8080
    volumes:
        - type: volume
          source: recordings
          target: /recordings
    restart: always

  db:
    container_name: mariadb_container
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      backend-network:
    ports:
    - 3306:3306
    restart: always

networks:
  backend-network:
    driver: bridge

volumes:
  recordings:
  mariadb-data:
