version: "3.8"

services:
  streaming-server:
    container_name: streaming-server
    image: alfg/nginx-rtmp
    ports:
      - 1935:1935
      - 80:80
      - 443:443
    networks:
      backend-network:
    depends_on:
      - backend
    volumes:
      - type: volume
        source: recordings
        target: /recordings
      - ./streaming-backend/nginx.conf:/etc/nginx/nginx.conf.template
      - ./streaming-backend/certs:/etc/nginx/certs
    restart: always

  backend:
    container_name: backend_container
    depends_on:
      - db
    build: .
    networks:
      backend-network:
    volumes:
      - type: volume
        source: recordings
        target: /recordings
    env_file:
      - variables-backend.env
      - hash.env
    restart: always

  db:
    container_name: mariadb_container
    image: mariadb
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      TZ: Europe/Berlin
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
      - mariadb-data:/var/lib/mysql
    networks:
      backend-network:
    ports:
      - 3306:3306
    restart: always

networks:
  backend-network:
    driver: bridge

volumes:
  recordings:
  mariadb-data:
